import {
  SiAxios,
  SiBootstrap,
  SiCodeigniter,
  SiComposer,
  SiCss,
  SiDocker,
  SiEslint,
  SiExpress,
  SiFirebase,
  SiGin,
  SiGithub,
  SiGo,
  SiGooglecloud,
  SiHtml5,
  SiJavascript,
  SiJenkins,
  SiJest,
  SiJetpackcompose,
  SiJira,
  SiKotlin,
  SiLaravel,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiNpm,
  SiPhp,
  SiPinia,
  SiPostgresql,
  SiPostman,
  SiReact,
  SiRedis,
  SiRedux,
  SiSass,
  SiSupabase,
  SiSwagger,
  SiTailwindcss,
  SiTypescript,
  SiVite,
  SiVitest,
  SiVuedotjs,
  SiYarn
} from "react-icons/si"
import { GiBearHead } from "react-icons/gi";
import { TbBeach, TbBrandFramerMotion } from "react-icons/tb";
import { FaAws } from "react-icons/fa6";

export const skillIcons = {
  SiHtml5,
  SiCss,
  SiSass,
  SiBootstrap,
  SiTailwindcss,
  SiJavascript,
  SiTypescript,
  SiVuedotjs,
  SiReact,
  SiNextdotjs,
  SiVite,
  SiPinia,
  SiRedux,
  SiZustand: GiBearHead,
  SiTanStackQuery: TbBeach,
  SiAxios,
  SiEslint,
  SiVitest,
  SiJest,
  SiMotion: TbBrandFramerMotion,
  SiNodedotjs,
  SiExpress,
  SiGo,
  SiGin,
  SiPhp,
  SiLaravel,
  SiCodeigniter,
  SiPostgresql,
  SiMysql,
  SiFirebase,
  SiSupabase,
  SiPostman,
  SiSwagger,
  SiRedis,
  SiKotlin,
  SiJetpackcompose,
  SiDocker,
  SiGooglecloud,
  FaAws,
  SiGithub,
  SiJenkins,
  SiJira,
  SiNpm,
  SiYarn,
  SiComposer
}