import { IconType } from "react-icons";
import {
  SiAndroid,
  SiAngular,
  SiAxios,
  SiBootstrap,
  SiCodeigniter,
  SiComposer,
  SiConfluence,
  SiCss,
  SiDocker,
  SiExpress,
  SiFigma,
  SiFirebase,
  SiGin,
  SiGit,
  SiGithub,
  SiGo,
  SiGooglecloud,
  SiGooglegemini,
  SiGradle,
  SiHtml5,
  SiJavascript,
  SiJenkins,
  SiJest,
  SiJetpackcompose,
  SiJira,
  SiKotlin,
  SiLaravel,
  SiLinux,
  SiMiro,
  SiMysql,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiNpm,
  SiPhp,
  SiPinia,
  SiPostgresql,
  SiPostman,
  SiReact,
  SiRedis,
  SiRedux,
  SiSass,
  SiSupabase,
  SiSwagger,
  SiTailwindcss,
  SiTrello,
  SiTypescript,
  SiVite,
  SiVitest,
  SiVuedotjs,
  SiYarn,
} from "react-icons/si"
import { GiBearHead, GiChameleonGlyph } from "react-icons/gi"
import { TbBeach, TbBrandFramerMotion, TbFileTypeXml } from "react-icons/tb"
import { FaAws } from "react-icons/fa6"
import { BiLogoAdobe } from "react-icons/bi"

export const SkillIconMap : Record<string, IconType> = {
  SiHtml5,
  SiCss,
  SiSass,
  SiBootstrap,
  SiTailwindcss,
  SiJavascript,
  SiTypescript,
  SiVuedotjs,
  SiReact,
  SiAngular,
  SiNextdotjs,
  SiVite,
  SiPinia,
  SiRedux,
  SiZustand: GiBearHead,
  SiTanStackQuery: TbBeach,
  SiAxios,
  SiVitest,
  SiJest,
  SiMotion: TbBrandFramerMotion,
  SiNodedotjs,
  SiExpress,
  SiGo,
  SiGin,
  SiPhp,
  SiLaravel,
  SiCodeigniter,
  SiPostgresql,
  SiMysql,
  SiFirebase,
  SiSupabase,
  SiPostman,
  SiSwagger,
  SiRedis,
  SiKotlin,
  SiJetpackcompose,
  SiAndroidView: TbFileTypeXml,
  SiAndroid,
  SiGradle,
  SiFigma,
  SiAdobe: BiLogoAdobe,
  SiStyleDictionary: GiChameleonGlyph,
  SiJira,
  SiConfluence,
  SiTrello,
  SiMiro,
  SiDocker,
  SiGooglecloud,
  SiAws: FaAws,
  SiGit,
  SiGithub,
  SiGooglegemini,
  SiJenkins,
  SiLinux,
  SiNginx,
  SiNpm,
  SiYarn,
  SiComposer,
}
